default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_test


production:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
